apiVersion: apps/v1
kind: Deployment

metadata:
  name: streaming-service
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.streaming.replicas }}

  selector:
    matchLabels:
      app: streaming-service

  template:
    metadata:
      labels:
        app: streaming-service

    spec:
      containers:
      - name: streaming-service
        image: {{ .Values.streaming.image }}

        ports:
        - containerPort: {{ .Values.streaming.port }}

        env:
        - name: PORT
          value: "{{ .Values.streaming.port }}"

        - name: MONGO_URI
          value: "mongodb://mongo:27017/streamingapp"

        - name: JWT_SECRET
          value: "{{ .Values.jwtSecret }}"

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service

metadata:
  name: streaming-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: streaming-service

  ports:
  - port: {{ .Values.streaming.port }}
    targetPort: {{ .Values.streaming.port }}
